version: '2'

services:
  postgresqldb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root123
      - POSTGRES_USER=cmsuser
      - POSTGRES_DB=postgres
    networks:
      - cms-net
  redis:
    container_name: redis
    image: redis:latest
    command: ["redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    networks:
      - cms-net
  app:
    image: cms
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - "somehost:192.168.1.7"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=cmsuser
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgresqldb
      - redis
    networks:
      - cms-net
networks:
  cms-net:
    external: true

    
   
     
    

